### ISSUE TITLE
Styles in loops

### ISSUE THREAD

**Issue by ajstarks** [taironas/tinygraphs#97]
In general it's better to define a style outside of a loop, and then apply it instead of repeating it. For example instead of 

    for ... {
        style := ....
        canvas.Line(...., style)
    }

do this:

    canvas.Gstyle(fmt.Spintf(.....)
    for ... {
        canvas.Line(....)
    }
    canvas.Gend()

**Comment by santiaago** [comment]
Interesting, I will give it a try, 
thanks for the feedback.

**Comment by santiaago** [comment]
@ajstarks when the I use the same style over the whole loop it definitly makes sense to use `canvas.Gstyle()`, Thanks.

In the case of multiple styles in the same loop it is a bit harder as you would have to create a loop for each style.

Should I also try to use Gstyle in this type of scenario?
~~~~go
for ... {
    style1 := ....
    style2 := ....
    if something {
        canvas.Line(...., style1)
    } else { 
        canvas.Line(..., style2)
    }
}
~~~~

**Comment by ajstarks** [comment]
Nah, it's not worth it in the case you cite.  Gstyle is useful for invariants.  However, *if* you can make the decision outside of the loop, you can assign two styles before the loop and then apply them.
 
```go
      style1 := ....
      style2 := ...
      for ... {
         if something {
              canvas.Line(...., style1)
          } else {
              canvas.LIne(...., style2)
         }
     }
```

Another useful pattern is to combine Gstyle() for the common style items, and then add variation in the loop as needed.

**Comment by santiaago** [comment]
Cool, thanks

I was able to clean some of the roots where I was creating a fill each time.
See --> 60203d4b98f7d76ad40dcdb9474b349c8ed7f04d

And I also manage to use the pattern you described (Gstyle() then add variations).
See --> c6cafeb25ce282cf474f4865e5c4013fcb22a509

**Comment by ajstarks** [comment]
in revision c6cafeb  you can eliminate the var fill, and then do:

```go
    if colorIndex[yL] == 0 {
        canvas.Polygon(xs, ys, draw.FillFromRGBA(colorMap[yL]))
    }
```

**Comment by santiaago** [comment]
good spot, I will simplify that :+1:
